apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: openshift-pipelines-1-23-bundle-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
    releaseNotes:
      type: "RHSA"
    mapping:
      defaults:
        tags:
          - "v1.23.0-stage"
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-bundle-1-23-stage-rp
  snapshot: openshift-pipelines-bundle-1-23-20260714-073506-000
