apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    pipelinesascode.tekton.dev/cancel-in-progress: "true" # Cancel in-progress pipelines
    {{- if  and (ne .Repository.Branch.Name "next") (contains "index" .Name ) }}
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/openshift-pipelines/operator/refs/heads/next/.tekton/fbc-build.yaml"
    {{- else }}{{- if  or (ne .Repository.Branch.Name "next") (ne .Repository.Name "operator") }}
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/openshift-pipelines/operator/refs/heads/next/.tekton/docker-build-ta.yaml"
    {{- end }}
    {{- end }}
    build.appstudio.openshift.io/repo: {{.Repository.Url}}?rev={{"{{revision}}"}}
    build.appstudio.redhat.com/commit_sha: '{{"{{revision}}"}}'
    build.appstudio.redhat.com/pull_request_number: '{{"{{pull_request_number}}"}}'
    build.appstudio.redhat.com/target_branch: '{{"{{target_branch}}"}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "{{.Repository.Branch.Name}}" &&
      ({{.Tekton.WatchedSources}} ||
      "{{.Dockerfile}}".pathChanged() ||
      {{- if  and (eq .Repository.Branch.Name "next")  (eq .Repository.Name "tektoncd-operator") }} ".tekton/*build*.yaml".pathChanged() || {{- end }}
      ".tekton/{{basename .Repository.Name | hyphenize}}-{{hyphenize .Version.Version}}-{{.Name}}-pull-request.yaml".pathChanged())
  labels:
    appstudio.openshift.io/application: {{hyphenize .Application.Name}}-{{hyphenize .Version.Version}}
    appstudio.openshift.io/component: {{basename .Repository.Name | hyphenize}}-{{hyphenize .Version.Version}}-{{hyphenize .Name}}
    pipelines.appstudio.openshift.io/type: build
  name: {{basename .Repository.Name | hyphenize}}-{{hyphenize .Version.Version}}-{{.Name}}-on-pull-request
  namespace: {{.Application.Namespace}}
spec:
  params:
  - name: git-url
    value: '{{"{{source_url}}"}}'
  - name: upstream-git-url
    value: 'https://github.com/{{.Repository.Upstream}}'
  - name: revision
    value: '{{"{{revision}}"}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/{{.Application.Namespace}}/{{.Image}}:on-pr-{{"{{revision}}"}}
  - name: image-expires-after
    value: 5d
  - name: dockerfile
    value: {{.Dockerfile}}
  - name: additional-tags
    value:
      - "on-pr-{{- .Application.Release.PatchVersion}}"
  - name: build-platforms
    value:
    - linux/x86_64
  {{- if eq "bundle" .Name }}
  - name: build-image-index
    value: false
  {{end }}
  {{- if  not (contains "index" .Name) }}
  - name: prefetch-input
    value: |
      {{.PrefetchInput}}
  {{- end }}
  pipelineRef:
    name:
  {{- if  not (contains "index" .Name) }} docker-build-ta
  {{- else}} fbc-build {{- end }}
  taskRunTemplate:
    serviceAccountName: build-pipeline-{{basename .Repository.Name | hyphenize}}-{{hyphenize .Version.Version}}-{{hyphenize .Name}}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{"{{ git_auth_secret }}"}}'
status: {}
