---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: multikueue-hub-setup1
spec:
  workspaces:
    - name: credentials
  params:
    - name: IMAGE
      default: quay.io/openshift-pipeline/ci
    - name: MULTI_CLUSTER_ROLE
      default: "Hub"
    - name: KUEUE_NAMESPACE
      default: "openshift-kueue-operator"
    - name: KUBECONFIG
      default: kubeconfig
    - name: SPOKES
      type: array
  stepTemplate:
    image: $(params.IMAGE)
    env:
      - name: KUEUE_NAMESPACE
        value: $(params.KUEUE_NAMESPACE)
      - name: KUBECONFIG
        value: $(workspaces.credentials.path)/$(params.KUBECONFIG)
  steps:
    - name: create-spoke-secrets-and-clusters
      results:
        - name: spoke
      args:
        - "$(params.SPOKES)"
      script: |
        #!/usr/bin/env bash
        set -x
        
        # Loop through the array passed in via args
        for spoke in "$@"; do
          spoke=$(echo "$spoke" | tr -d '\n' | xargs)
          echo "Current spoke: $spoke"
          echo "Current spoke secret-name: ${spoke/./-}"
          kubectl create secret generic "${spoke/./-}" --from-file=kubeconfig=$(workspaces.credentials.path)/${spoke} -n  $KUEUE_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
        cat <<EOF | kubectl apply -f -
          apiVersion: kueue.x-k8s.io/v1beta2
          kind: MultiKueueCluster
          metadata:
            name: ${spoke/./-}
          spec:
            clusterSource:
              kubeConfig:
                locationType: Secret
                location: ${spoke/./-}
        EOF
        echo -n ${spoke/./-} | tee $(step.results.spoke.path)
        done
    - name: configure-rbac-for-tekton
      script: |
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRole
        metadata:
          name: kueue-tekton-permissions
        rules:
          - apiGroups:
              - tekton.dev
            resources:
              - pipelineruns
              - pipelineruns/status
            verbs:
              - create
              - delete
              - get
              - list
              - patch
              - update
              - watch
        ---
        apiVersion: rbac.authorization.k8s.io/v1
        kind: ClusterRoleBinding
        metadata:
          name: kueue-tekton-permissions-binding
        roleRef:
          apiGroup: rbac.authorization.k8s.io
          kind: ClusterRole
          name: kueue-tekton-permissions
        subjects:
          - kind: ServiceAccount
            name: kueue-controller-manager
            namespace: $KUEUE_NAMESPACE
        EOF

    - name: apply-multikueue-hub-resources
      env:
        - name: SPOKE_CLUSTER
          value: $(steps.create-spoke-secrets-and-clusters.results.spoke)
      script: |
        cat <<EOF | kubectl apply -f -
        apiVersion: kueue.x-k8s.io/v1beta2
        kind: ResourceFlavor
        metadata:
          name: "default-flavor"
        ---
        apiVersion: kueue.x-k8s.io/v1beta2
        kind: ClusterQueue
        metadata:
          name: "cluster-queue"
        spec:
          namespaceSelector: {}
          resourceGroups:
          - coveredResources: ["cpu", "memory", "tekton.dev/pipelineruns"]
            flavors:
            - name: "default-flavor"
              resources:
              - name: "cpu"
                nominalQuota: 9
              - name: "memory"
                nominalQuota: 36Gi
              - name: "tekton.dev/pipelineruns"
                nominalQuota: "10"
          admissionChecksStrategy:
            admissionChecks:
              - name: sample-multikueue
        ---
        apiVersion: kueue.x-k8s.io/v1beta2
        kind: LocalQueue
        metadata:
          name: "pipelines-queue"
        spec:
          clusterQueue: "cluster-queue"
        ---
        apiVersion: kueue.x-k8s.io/v1beta2
        kind: AdmissionCheck
        metadata:
          name: sample-multikueue
        spec:
          controllerName: kueue.x-k8s.io/multikueue
          parameters:
            apiGroup: kueue.x-k8s.io
            kind: MultiKueueConfig
            name: multikueue-test
        ---
        apiVersion: kueue.x-k8s.io/v1beta2
        kind: MultiKueueConfig
        metadata:
          name: multikueue-test
        spec:
          clusters:
            - $SPOKE_CLUSTER
        EOF


    - name: enable-multi-cluster
      script: |
        set -x
        kubectl patch tektonconfig config --type='merge' -p '
        {
          "spec": {
            "scheduler": {
              "disabled": false,
              "multi-cluster-disabled": false,
              "multi-cluster-role": "$(params.MULTI_CLUSTER_ROLE)"
            }
          }
        }'
    - name: verification
      env:
        - name: SPOKE_CLUSTER
          value: $(steps.create-spoke-secrets-and-clusters.results.spoke)
      script: |
        echo "Step: verification: $SPOKE_CLUSTER"
        spoke=$(echo "$SPOKE_CLUSTER" | tr -d '\n' | xargs)
        echo "Current spoke: $spoke"
        kubectl get multikueuecluster ${spoke} \
        -o jsonpath="{range .status.conditions[?( @.type == \"Active\")]}MC - Active: { @.status} Reason: { @.reason} Message: { @.message}{'\n'}{end}"
