---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: multikueue-spoke-setup
spec:
  workspaces:
    - name: credentials
  results:
    - name: sa-kubeconfig
  params:
    - name: IMAGE
      default: quay.io/openshift-pipeline/ci
    - name: CLUSTER_INFO
      default: "{}"
  stepTemplate:
    image: $(params.IMAGE)
    env:
      - name: KUEUE_NAMESPACE
        value: openshift-kueue-operator
      - name: CLUSTER_INFO
        value: $(params.CLUSTER_INFO)
      - name: SA_NAMESPACE
        value: default
  steps:
    - name: parse-cluster-info
      results:
        - name: cluster-name
        - name: kubeconfig
      script: |
        set -x 
        echo $CLUSTER_INFO
        echo -n "$CLUSTER_INFO" | jq -r .name | tr -d '\n'| tee $(step.results.cluster-name.path)
        echo -n "$CLUSTER_INFO" | jq -r .kubeconfig | tr -d '\n'| tee $(step.results.kubeconfig.path)

    - name: create-service-account
      env:
        - name: KUBECONFIG
          value: $(workspaces.credentials.path)/$(steps.parse-cluster-info.results.kubeconfig)
      script: |
        echo "Create ServiceAccount |$KUBECONFIG|"
        kubectl create sa multikueue-sa -n $SA_NAMESPACE --dry-run=client -o yaml | kubectl apply -f -
        echo "Create ClusterRole"
        cat <<EOF | kubectl apply -f -
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRole
          metadata:
            name: multikueue-sa-role
          rules:
            - apiGroups: [""]
              resources: ["pods"]
              verbs: ["get", "list", "watch", "create", "delete"]
            - apiGroups: ["batch"]
              resources: ["jobs"]
              verbs: ["get", "list", "watch", "create", "delete"]
            - apiGroups: ["kueue.x-k8s.io"]
              resources: ["workloads", "workloads/status"]
              verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
            - apiGroups: ["tekton.dev"]
              resources: ["pipelineruns", "pipelineruns/status"]
              verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
        EOF
        
        echo "Bind Role to ServiceAccount"
        kubectl create clusterrolebinding multikueue-sa-crb \
            --clusterrole=multikueue-sa-role \
            --serviceaccount=$SA_NAMESPACE:multikueue-sa --dry-run=client -o yaml | kubectl apply -f -
    - name: generate-kube-config
      env:
        - name: KUBECONFIG
          value: $(workspaces.credentials.path)/$(steps.parse-cluster-info.results.kubeconfig)
        - name: CLUSTER_NAME
          value: $(steps.parse-cluster-info.results.cluster-name)
      script: |
        set -x
        cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Secret
          type: kubernetes.io/service-account-token
          metadata:
            name: multikueue-sa-token
            namespace: $SA_NAMESPACE
            annotations:
              kubernetes.io/service-account.name: "multikueue-sa"
        EOF
        
        echo "Wait for token population" 
        sleep 10
        
        echo "Extract Token and CA Certificate"
        SA_TOKEN=$(kubectl -n $SA_NAMESPACE get secret multikueue-sa-token  -o jsonpath='{.data.token}' | base64 -d)
        CA_CERT=$(kubectl -n $SA_NAMESPACE get secret multikueue-sa-token  -o jsonpath='{.data.ca\.crt}')
        SERVER_URL=$(kubectl -n $SA_NAMESPACE config view --minify -o jsonpath='{.clusters[0].cluster.server}')
        
        echo "Create Kubeconfig file"
        SA_KUBECONFIG_FILE=sa-${CLUSTER_NAME}.kubeconfig
        cat <<EOF >  $(workspaces.credentials.path)/$SA_KUBECONFIG_FILE
          apiVersion: v1
          clusters:
            - cluster:
                server: ${SERVER_URL}
                certificate-authority-data: ${CA_CERT}
              name: ${CLUSTER_NAME}-cluster
          contexts:
            - context:
                cluster: ${CLUSTER_NAME}-cluster
                user: multikueue-sa
              name: ${CLUSTER_NAME}-context
          current-context: ${CLUSTER_NAME}-context
          kind: Config
          preferences: {}
          users:
            - name: multikueue-sa
              user:
                token: ${SA_TOKEN}
        EOF
        echo -n $SA_KUBECONFIG_FILE | tee $(results.sa-kubeconfig.path)  

