apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tekton-ecosystem-tenant
  name: release-plan-role-next
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: tekton-ecosystem-tenant
  name: release-plan-rolebinding-next
subjects:
- kind: ServiceAccount
  name: release-registry-openshift-pipelines-next
  apiGroup: ""
roleRef:
  kind: Role
  name: release-plan-role-next
  apiGroup: rbac.authorization.k8s.io
