kind: Secret
apiVersion: v1
metadata:
  name: release-registry-openshift-pipelines-next
  namespace: tekton-ecosystem-tenant
  annotations:
    tekton.dev/docker-0: https://quay.io
data:
  username: xyz
  password: abc
type: kubernetes.io/basic-auth