repository: console-plugin
components:
  - name: console-plugin
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
  - name: release-v1.17.x
    versions:
    - version: next
      release: auto
    - version: "1.18"
