repository: console-plugin
components:
  - name: console-plugin
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: release-v1.17.x
    release: auto
  - version: "1.18"
    branch: main
