repository: ecosystem-images
components:
  - name: opc
  - name: git-init
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
    versions:
    - version: main
    - version: next
      release: auto
    - version: "1.18"
