repository: ecosystem-images
components:
  - name: opc
  - name: git-init
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: main
    release: auto
  - version: "1.18"
    branch: main
