repository: manual-approval-gate
components:
  - name: controller
  - name: webhook
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: main
    release: auto
  - version: "1.18"
    branch: release-v0.5.0