repository: manual-approval-gate
components:
  - name: controller
  - name: webhook
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
  - name: release-v0.5.0
    versions:
    - version: next
      release: auto
    - version: "1.18"
