repository: manual-approval-gate
components:
  - controller
  - webhook
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: release-v0.4.1
    release: auto
  - version: "1.18"
    branch: main