repository: manual-approval-gate
components:
  # Image name patten in Comment includes prefix "manual-approval-gate-". To match the generated images we need to add Image Prefix here.
  - name: controller
    image-prefix: manual-approval-gate-
  - name: webhook
    image-prefix: manual-approval-gate-
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  # uncomment below line to get nightly builds
  # - name: main
  - name: release-v0.5.0
    versions:
    - version: next
      release: auto
    - version: "1.18"
