name: openshift-pipelines
versions:
  1.15:
    version: 1.15
    image-suffix: -rhel8
resources:
  - console-plugin
  - manual-approval-gate
  - pac-downstream
  - tektoncd-triggers
  - tektoncd-pipeline
  - tektoncd-chains
  - tektoncd-cli
  - tektoncd-hub
  - tektoncd-results
  - operator
  - git-init
