repository: pac-downstream
upstream: openshift-pipelines/pipelines-as-code
components:
  - controller
  - webhook
  - watcher
  - cli
branches:
  - upstream: release-v0.32.x
    version: next
    release: auto
  - upstream: release-v0.32.x
    version: "1.18"
