repository: pac-downstream
upstream: openshift-pipelines/pipelines-as-code
components:
  - name: controller
  - name: webhook
  - name: watcher
  - name: cli
branches:
  - upstream: release-v0.32.x
    version: next
    release: auto
  - upstream: release-v0.32.x
    version: "1.18"
