repository: pac-downstream
upstream: openshift-pipelines/pipelines-as-code
components:
  - name: controller
  - name: webhook
  - name: watcher
  - name: cli
    nudges:
      - operator-{{hyphenize .Version}}-bundle
      - tektoncd-cli-{{hyphenize .Version}}-tkn
branches:
  - name: main
  - name: next
    upstream: release-v0.32.x
    versions:
      - version: next
        release: auto
  - name: release-v1.18.x
    upstream: release-v0.32.x
    versions:
      - version: "1.18"
