repository: pac-downstream
upstream: openshift-pipelines/pipelines-as-code
components:
  - name: controller
  - name: webhook
  - name: watcher
  - name: cli
branches:
  - name: main
    versions:
    - version: main
    - version: next
      release: auto
    - version: "1.18"
