repository: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
  - controller
  - entrypoint
  - events
  - nop
  - resolvers
  - sidecarlogresults
  - webhook
  - workingdirinit
branches:
  - upstream: release-v0.65.x
    version: next
    release: auto
  - upstream: release-v0.68.x
    version: "1.18"
