repository: tektoncd-hub
upstream: tektoncd/hub
components:
  - db-migration
  - hub-api
  - hub-ui
branches:
  - upstream: release-v1.19.2
    version: next
    release: auto
  - upstream: main
    version: "1.18"