repository: tekton-caches
components:
  - cache
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: release-v1.18.x
    release: auto
  - version: "1.18"
    branch: release-v1.18.x
