repository: tektoncd-results
upstream: tektoncd/results
components:
  - api
  - watcher
  - retention-policy-agent
branches:
  - upstream: release-v0.13.x
    version: next
    release: auto
  - upstream: release-v0.14.x
    version: "1.18"
