repository: tektoncd-triggers
upstream: tektoncd/triggers
components:
  - name: controller
  - name: webhook
  - name: core-interceptors
  - name: eventlistenersink
branches:
  - name: main
  - name: next
    upstream: release-v0.31.x
    versions:
      - version: next
        release: auto
  - name: release-v1.18.x
    upstream: release-v0.31.x
    versions:
      - version: "1.18"
