repository: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
  - name: controller
  - name: entrypoint
  - name: events
  - name: nop
  - name: resolvers
  - name: sidecarlogresults
  - name: webhook
  - name: workingdirinit
branches:
  - name: main
  - name: next
    upstream: release-v0.65.x
    versions:
      - version: next
        release: auto
      - version: "1.18"
