repository: tektoncd-hub
upstream: tektoncd/hub
components:
  - db-migration
  - hub-api
  - hub-ui
branches:
  - upstream: release-v1.20.0
    version: next
    release: auto
  - upstream: release-v1.20.0
    version: "1.18"