repository: tektoncd-hub
upstream: tektoncd/hub
components:
  - name: db-migration
  - name: hub-api
  - name: hub-ui
    prefetch-input: |-
      {"type": "npm", "path": "upstream/ui"}
branches:
  - upstream: release-v1.20.0
    version: next
    release: auto
  - upstream: release-v1.20.0
    version: "1.18"