repository: tektoncd-pruner
components:
  - name: controller
  - name: webhook
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
  - name: next
    versions:
      - version: next
        release: auto
