repository: tekton-caches
components:
  - name: cache
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
  - name: release-v0.1.x
    versions:
      - version: next
        release: auto
      - version: "1.18"
