repository: tektoncd-pipeline
upstream: tektoncd/pipeline
components:
  - name: controller
  - name: entrypoint
  - name: events
  - name: nop
  - name: resolvers
  - name: sidecarlogresults
  - name: webhook
  - name: workingdirinit
branches:
  - upstream: release-v0.68.x
    version: next
    release: auto
  - upstream: release-v0.68.x
    version: "1.18"
