repository: tektoncd-results
upstream: tektoncd/results
components:
  - name: api
  - name: watcher
  - name: retention-policy-agent
branches:
  - name: main
  - name: next
    upstream: release-v0.14.x
    versions:
      - version: next
        release: auto
  - name: release-v1.18.x
    upstream: release-v0.14.x
    versions:
      - version: "1.18"
