repository: tektoncd-pruner
components:
  - name: controller
  - name: webhook
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - name: main
    versions:
      - version: main
      - version: next
        release: auto
