repository: tekton-caches
components:
  - name: cache
tekton:
  watched-sources: '"***".pathChanged()'
branches:
  - version: next
    branch: release-v0.1.x
    release: auto
  - version: "1.18"
    branch: release-v0.1.x
