repository: tektoncd-triggers
upstream: tektoncd/triggers
components:
  - controller
  - webhook
  - core-interceptors
  - eventlistenersink
branches:
  - upstream: release-v0.31.x
    version: next
    release: auto
  - upstream: release-v0.31.x
    version: "1.18"
