repository: tektoncd-hub
upstream: tektoncd/hub
components:
  - name: db-migration
  - name: hub-api
  - name: hub-ui
    prefetch-input: |-
      {"type": "npm", "path": "upstream/ui"}
branches:
  - name: main
  - name: next
    upstream: release-v1.19.2
    versions:
      - version: next
        release: auto
      - version: "1.18"