repository: tektoncd-hub
upstream: tektoncd/hub
components:
  - name: db-migration
  - name: api
  - name: ui
    prefetch-input: |-
      [{"type": "npm", "path": "upstream/ui"}, {"type": "rpm", "path": ".konflux/rpms"}]
branches:
  # uncomment below line to get nightly builds
  # - name: main
  - name: next
    upstream: release-v1.20.0
    versions:
      - version: next
  - name: release-v1.18.x
    upstream: release-v1.20.0
    versions:
      - version: "1.18"
