repository: tektoncd-chains
upstream: tektoncd/chains
components:
  - name: controller
branches:
  - name: main
  - name: next
    upstream: release-v0.24.x
    versions:
      - version: next
  - name: release-v1.18.x
    upstream: release-v0.24.x
    versions:
      - version: "1.18"
