version: "1.15"
image-suffix: -rhel9
patch-version: 1.15.5
branches:
  git-init:
    upstream: release-v1.0.x
  manual-approval-gate:
    upstream: release-v0.2.2
  opc:
    upstream: release-v1.15.x
  pipelines-as-code:
    upstream: release-v0.27.x
  tektoncd-chains:
    upstream: release-v0.20.x
  tektoncd-cli:
    upstream: release-v0.37.4
  tektoncd-hub:
    upstream: release-v1.17.5
  tektoncd-pipeline:
    upstream: release-v0.59.x
  tektoncd-results:
    upstream: release-v0.10.x
  tektoncd-triggers:
    upstream: release-v0.27.x
  operator:
    upstream: release-v0.71.x
