version: "1.20"
image-suffix: -rhel9
patch-version: 1.20.5
code-freeze: true
branches:
  git-init:
    upstream: release-v1.2.x
  manual-approval-gate:
    upstream: release-v0.7.0
  opc:
    upstream: release-v1.20.x
  pipelines-as-code:
    upstream: release-v0.37.x
  tekton-assist:
    upstream: release-v0.1.x
  tekton-caches:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.25.x
  tektoncd-cli:
    upstream: release-v0.42.1
  tektoncd-hub:
    upstream: release-v1.22.10
  tektoncd-pipeline:
    upstream: release-v1.3.x
  tektoncd-pruner:
    upstream: release-v0.2.x
  tektoncd-results:
    upstream: release-v0.16.x
  tektoncd-triggers:
    upstream: release-v0.33.x
  operator:
    upstream: release-v0.77.x
