version: 1.23
release-tag: 1.23.0
image-suffix: "-rhel9"
code-freeze: false
branches:
  git-init:
    upstream: main
  manual-approval-gate:
    upstream: release-v0.9.0
  opc:
    upstream: release-v1.23.x
  pipelines-as-code:
    upstream: release-v0.48.x
  console-plugin-pf5:
    upstream: release-v1.22.x
  tekton-assist:
    upstream: main
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.27.x
  tektoncd-cli:
    upstream: release-v0.45.x
  tektoncd-hub:
    upstream: release-v1.24.1
  tektoncd-pipeline:
    upstream: release-v1.12.x
  tektoncd-pruner:
    upstream: release-v0.4.x
  tektoncd-results:
    upstream: release-v0.19.x
  tektoncd-triggers:
    upstream: release-v0.36.x
  syncer-service:
    upstream: release-v0.1.x
  multicluster-proxy-aae:
    upstream: release-v0.1.x
  operator:
    upstream: release-v0.80.x
