version: "1.24"
image-suffix: -rhel9
patch-version: 1.24.0
branches:
  git-init:
    upstream: release-v1.2.x
  manual-approval-gate:
    upstream: release-v0.8.0
  multicluster-proxy-aae:
    upstream: release-v0.1.x
  opc:
    upstream: release-v1.22.x
  pipelines-as-code:
    upstream: release-v0.45.x
  syncer-service:
    upstream: release-v0.1.x
  tekton-assist:
    upstream: release-v0.1.x
  tekton-caches:
    upstream: release-v0.3.x
  tekton-kueue:
    upstream: release-v0.3.x
  tektoncd-chains:
    upstream: release-v0.26.x
  tektoncd-cli:
    upstream: release-v0.44.1
  tektoncd-hub:
    upstream: release-v1.23.9
  tektoncd-pipeline:
    upstream: release-v1.11.x
  tektoncd-pruner:
    upstream: release-v0.3.x
  tektoncd-results:
    upstream: release-v0.18.x
  tektoncd-triggers:
    upstream: release-v0.35.x
  operator:
    upstream: main
