version: nightly
release-tag: latest
image-suffix: "-rhel10"
code-freeze: false
docker-file-options:
  args:
    GO_BUILDER: "registry.access.redhat.com/ubi10/go-toolset:latest@sha256:be70aa468168f1ecd46e56d5f362e697243bcf9d3a2d98819597e43471a5d0e4"
    NJS_BUILDER: "registry.access.redhat.com/ubi10/nodejs-24:latest@sha256:0422012ca2c02075b6556cf4ad0dcea8d51de7b33854548ff83d8fe4d17449d8"
    NGX_RUNTIME: "registry.access.redhat.com/ubi10/nginx-126:latest@sha256:f9ebfcd934f59bf1963b1e0b13c9b77c44abff4af6c2b18680c8ce1f087d01ea"
branches:
  console-plugin-pf5:
    upstream: main
  console-plugin:
    upstream: master
