apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-core-1-16
    pac.test.appstudio.openshift.io/event-type: push
    pac.test.appstudio.openshift.io/url-org: openshift-pipelines
    release.appstudio.openshift.io/author: rh-ee-sashture
  generateName: openshift-pipelines-core-1-16-4-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
    releaseNotes:
      description: |
        Red Hat OpenShift Pipelines is a cloud-native continuous integration and
        delivery (CI/CD) solution for building pipelines using Tekton. Tekton is a
        flexible, Kubernetes-native, open-source CI/CD framework which enables
        automating deployments across multiple platforms such as Kubernetes, Serverless,
        and VMs by abstracting away the underlying details.
      issues:
        fixed:
          - id: SRVKP-7662
            source: issues.redhat.com
          - id: SRVKP-7653
            source: issues.redhat.com
          - id: SRVKP-7077
            source: issues.redhat.com
          - id: SRVKP-7495
            source: issues.redhat.com
          - id: SRVKP-7494
            source: issues.redhat.com
          - id: SRVKP-7493
            source: issues.redhat.com
          - id: SRVKP-7492
            source: issues.redhat.com
          - id: SRVKP-6406
            source: issues.redhat.com
          - id: SRVKP-6338
            source: issues.redhat.com
          - id: SRVKP-6303
            source: issues.redhat.com
          - id: SRVKP-7491
            source: issues.redhat.com
      package-maintainer: pipelines-bots@redhat.com
      references:
        - https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines
      release-name: openshift-pipelines-1.16.4
      solution: |
        Before applying this update, make sure all previously released advisory
        relevant to your system have been applied.
        For details on how to apply this update, refer to:
        https://access.redhat.com/articles/11258
      synopsis: "Red Hat OpenShift Pipelines Release 1.16.4"
      topic: |
        The 1.16.4 release of Red Hat OpenShift Pipelines Operator..
        For more details see [product documentation](https://docs.redhat.com/en/documentation/red_hat_openshift_pipelines).
      type: RHBA
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-core-1-16-stage-release-as-op
  snapshot: openshift-pipelines-core-1-16-kdqbb