apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  generateName: openshift-pipelines-1-22-bundle-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
    releaseNotes:
      type: "RHSA"
    mapping:
      defaults:
        tags:
          - "v1.22.1-stage"
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-1-22-bundle-stage-release-as-op
  snapshot: openshift-pipelines-bundle-1-22-20260529-104334-000
