apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-1-20
  generateName: openshift-pipelines-index-1-20-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-index-1-20-stage-release-as-op
  snapshot: openshift-pipelines-index-1-20-20260415-062710-000
