---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: release-tests-multikueue-
spec:
  pipelineSpec:
    params:
      - name: RELEASE_TEST_TASKS_REPO
        default: https://github.com/openshift-pipelines/hack
      - name: RELEASE_TEST_TASKS_BRANCH
        default: multikueue
      - name: KUEUE_NAMESPACE
        default: "openshift-kueue-operator"
      - name: IMAGE
        default: quay.io/openshift-pipeline/ci:latest
      - name: SNAPSHOT
        default: ""
    workspaces:
      - name: credentials
    tasks:
      - name: check-config
        taskSpec:
          workspaces:
            - name: credentials
          steps:
            - name: print-config
              image: $(params.IMAGE)
              script:
                echo "Hello World"
                echo "Volume name" $(workspaces.credentials.volume)
      - name: parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/integration-examples
            - name: revision
              value: main
            - name: pathInRepo
              value: tasks/test_metadata.yaml
        params:
          - name: SNAPSHOT
            value: $(params.SNAPSHOT)
      - name: provision-eaas-space
        runAfter:
          - parse-metadata
        taskRef:
          resolver: git
          params:
            - name: url
              value: https://github.com/konflux-ci/build-definitions.git
            - name: revision
              value: main
            - name: pathInRepo
              value: task/eaas-provision-space/0.1/eaas-provision-space.yaml
        params:
          - name: ownerName
            value: $(context.pipelineRun.name)
          - name: ownerUid
            value: $(context.pipelineRun.uid)
      - name: provision-clusters
        runAfter:
          - provision-eaas-space
        #        matrix:
        #          params:
        #            - name: ROLE
        #              value: $(params.ROLES)
        taskRef:
          resolver: git
          params:
            - name: url
              value: $(params.RELEASE_TEST_TASKS_REPO)
            - name: revision
              value: $(params.RELEASE_TEST_TASKS_BRANCH)
            - name: pathInRepo
              value: release-tests/multikueue/tasks/task-provision-cluster.yaml
        params:
          - name: componentName
            value: "$(tasks.parse-metadata.results.component-name)"
          - name: EAAS_SPACE_SECRET_REF
            value: "$(tasks.provision-eaas-space.results.secretRef)"
          - name: INSTANCE_TYPE
            value: "$(params.INSTANCE_TYPE)"
      - name: get-kubeconfig
        runAfter:
          - provision-clusters
        taskSpec:
          workspaces:
            - name: credentials
          steps:
            - name: get-kubeconfig
              ref:
                resolver: git
                params:
                  - name: url
                    value: https://github.com/konflux-ci/build-definitions.git
                  - name: revision
                    value: main
                  - name: pathInRepo
                    value: stepactions/eaas-get-ephemeral-cluster-credentials/0.1/eaas-get-ephemeral-cluster-credentials.yaml
              params:
                - name: eaasSpaceSecretRef
                  value: $(tasks.provision-eaas-space.results.secretRef)
                - name: clusterName
                  value: "$(tasks.provision-clusters.results.clusterName)"
                - name: credentials
                  value:  $(workspaces.credentials.volume)
  workspaces:
    - name: credentials
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce # Standard mode for a single node reading/writing
          resources:
            requests:
              storage: 100Mi  # Specify the size of the PVC here