repo: p12n-console-plugin-pf5
upstream: openshift-pipelines/console-plugin
no-prefix-upstream: true
components:
  - name: console-plugin
    image-suffix: -pf5
    prefetch-input: |-
      [{"type": "rpm", "path": ".konflux/rpms"}, {"type": "yarn", "path": "upstream"}, {"type": "npm", "path": ".konflux/npm"}]
