name: operator
prefetch-input: "NONE"
min-version: 1.22
components:
  - name: index-5.0
    nudges: [ "" ]
    no-image-suffix: true
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
