name: operator
prefetch-input: "NONE"
max-version: 1.20
components:
  - name: index-4.14
    nudges: [ "" ]
    no-image-suffix: true
tekton:
  watched-sources: ( ".konflux/olm-catalog/index/***".pathChanged())
