name: tekton-kueue
upstream: tektoncd/tekton-kueue
no-prefix-upstream: true
min-version: 1.22
components:
  - name: kueue
    dockerfile: .konflux/dockerfiles/scheduler.Dockerfile
    prefetch-input: |
      {"type": "gomod", "path": "upstream"}
