apiVersion: v1
kind: Pod
metadata:
  name: image-copier-pod
spec:
  restartPolicy: Never
  containers:
    - name: runner
      image: alpine:latest
      command: ["/bin/sh", "-c"]
      args:
        - >
          echo "Installing dependencies..." &&
          apk add --no-cache bash skopeo jq &&
          echo "Preparing files..." &&
          cp /mnt/config/* /tmp/ &&
          chmod +x /tmp/copy-images.sh &&
          echo "Injecting TLS skip flag..." &&
          sed -i 's/skopeo copy --all/skopeo copy --all --src-tls-verify=false/g' /tmp/copy-images.sh &&
          cd /tmp &&
          ./copy-images.sh stage-images.json 1.22-stage-final
      volumeMounts:
        - name: config-volume
          mountPath: /mnt/config
          readOnly: true
        - name: auth-volume
          mountPath: /root/.docker
          readOnly: true
  volumes:
    - name: config-volume
      configMap:
        name: image-copier-data
    - name: auth-volume
      secret:
        secretName: skopeo-auth
        items:
          - key: .dockerconfigjson
            path: config.json