---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: {{hyphenize .Name}}-{{hyphenize .Version.Version}}-release-tests
labels:
  test.appstudio.openshift.io/optional: "true"
spec:
  application: {{hyphenize .Name}}-{{hyphenize .Version.Version}}
  contexts:
    - description: Application testing
      name: component_{{hyphenize .Name}}-{{hyphenize .Version.Version}}-index-4-18
  resolverRef:
    params:
      - name: url
        value: https://github.com/openshift-pipelines/operator
      - name: revision
        value: main
      - name: pathInRepo
        value: .konflux/tekton/bundle-e2e-pipeline.yaml
    resolver: git
