---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: {{.Name}}-{{hyphenize .Version}}-enterprise-contract-push
spec:
  application: {{.Name}}-{{hyphenize .Version}}
  contexts:
    - description: Application testing
      name: push
  params:
    - name: POLICY_CONFIGURATION
      value: tekton-ecosystem-tenant/tekton-ecosystem-tenant-containers
    - name: TIMEOUT
      value: "15m0s"
  resolverRef:
    params:
      - name: url
        value: "https://github.com/konflux-ci/build-definitions"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
