apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-bundle-1-24
  generateName: openshift-pipelines-bundle-1-24-prod-rp-
  namespace: tekton-ecosystem-tenant
spec:
  releasePlan: openshift-pipelines-bundle-1-24-prod-rp
  snapshot: openshift-pipelines-bundle-1-24-20260916-114632-000
