package konflux

type Config struct {
	Organization string `yaml:"organization"`
	Namespace    string `yaml:"namespace"`
	Applications []string
	Versions     []string
	Repositories []Repository `json:"repos" yaml:"repos"`
	ImagePrefix  string       `json:"image-prefix" yaml:"image-prefix"`
	ImageSuffix  string       `json:"image-suffix" yaml:"image-suffix"`
	Product      string       `json:"product" yaml:"product"`
}

type Application struct {
	Name            string
	Org             string
	Components      []Component
	Release         *Release
	Repositories    []Repository
	ReleaseToGitHub bool `yaml:"release-to-github"`
	AutoRelease     bool
	Namespace       string
	Config          Config
}

type Repository struct {
	Repo             string
	Name             string
	Upstream         string
	Url              string
	Branch           Branch
	Components       []Component
	Application      Application
	Tekton           Tekton
	GitHub           GitHub
	Patches          []Patch
	NoPrefixUpstream bool `json:"no-prefix-upstream" yaml:"no-prefix-upstream"`
	UsePatchBranch   bool `json:"use-patch-branch" yaml:"use-patch-branch"`
}
type Branch struct {
	Name           string
	UpstreamBranch string `json:"upstream" yaml:"upstream"`
	Patches        []Patch
}

type Component struct {
	Name             string
	Nudges           []string
	Dockerfile       string
	Image            string
	ImagePrefix      string `json:"image-prefix" yaml:"image-prefix"`
	ImageSuffix      string `json:"image-suffix" yaml:"image-suffix"`
	PrefetchInput    string `json:"prefetch-input" yaml:"prefetch-input"`
	Version          Release
	Repository       Repository
	Application      Application
	Tekton           Tekton
	NoImagePrefix    bool `json:"no-image-prefix" yaml:"no-image-prefix"`
	NoImageSuffix    bool `json:"no-image-suffix" yaml:"no-image-suffix"`
	NoPrefixUpstream bool `json:"no-prefix-upstream" yaml:"no-prefix-upstream"`
}

type Tekton struct {
	WatchedSources string `json:"watched-sources" yaml:"watched-sources"`
	EventType      string `json:"event_type" yaml:"event_type"`
	NudgeFiles     string `json:"build-nudge-files" yaml:"build-nudge-files"`
}

type GitHub struct {
	UpdateSources string `json:"update-sources" yaml:"update-sources"`
}

type Patch struct {
	Name   string
	Script string
}
type Release struct {
	Version      string
	PatchVersion string `json:"patch-version" yaml:"patch-version"`
	ImagePrefix  string `json:"image-prefix" yaml:"image-prefix"`
	ImageSuffix  string `json:"image-suffix" yaml:"image-suffix"`
	CodeFreeze   bool   `json:"code-freeze" yaml:"code-freeze"`
}

type ApplicationConfig struct {
	Repositories    []string `json:"repos" yaml:"repos"`
	Name            string
	Org             string
	ReleaseToGitHub bool `yaml:"release-to-github"`
	Namespace       string
}

type ReleaseConfig struct {
	Branches map[string]Branch `json:"branches" yaml:"branches"`
	Version  Release           `json:"version" yaml:",inline"`
}

const (
	konfluxDir          = ".konflux"
	gitHubDir           = ".github"
	tektonDir           = ".tekton"
	autoGeneratedHeader = "# Generated for Konflux Application {{.Name}} by openshift-pipelines/hack. DO NOT EDIT"
)
