package konflux

import (
	"context"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

func GenerateConfig(application Application, dryRun, generateTekton bool) error {
	if err := generateKonfluxConfig(application); err != nil {
		return err
	}
	if generateTekton {
		if err := generateRepositoryConfig(application, dryRun); err != nil {
			return err
		}
	}

	return nil
}

func generateRepositoryConfig(application Application, dryRun bool) error {
	log.Printf("Generating repository configuration")
	for _, repo := range application.Repositories {
		ctx := context.Background()
		var dir string
		var err error
		if dir, err = cloneAndCheckout(ctx, repo, filepath.Join("/tmp/konflux/", application.Config.Product)); err != nil {
			return err
		}
		if err := cleanupAutogenerated(ctx, application, dir, tektonDir); err != nil {
			return err
		}
		if application.Release.Version != "main" {
			if err := generateTektonConfig(repo, dir); err != nil {
				return err
			}
		}
		if err := generateGitHubConfig(repo, dir); err != nil {
			return err
		}

		if dryRun {
			log.Printf("Dry run enabled, not commiting changes to %s\n", application.Name)
		} else if err := commitAndPullRequest(ctx, repo, dir); err != nil {
			return err
		}
	}
	return nil

}

func generateTektonConfig(repo Repository, targetDir string) error {
	target := filepath.Join(targetDir, tektonDir)
	log.Printf("Generate tekton config in %s\n", target)

	if err := os.MkdirAll(target, 0o755); err != nil {
		return err
	}

	for _, c := range repo.Components {
		v := c.Version
		if err := generateFileFromTemplate("component-pull-request.yaml", c, filepath.Join(target, fmt.Sprintf("%s-%s-%s-pull-request.yaml", hyphenize(basename(c.Repository.Name)), hyphenize(v.Version), c.Name)), repo.Application); err != nil {
			return err
		}
		if err := generateFileFromTemplate("component-push.yaml", c, filepath.Join(target, fmt.Sprintf("%s-%s-%s-push.yaml", hyphenize(basename(c.Repository.Name)), hyphenize(v.Version), c.Name)), repo.Application); err != nil {
			return err
		}
		if err := MutateDockerFile(c, targetDir); err != nil {
			log.Printf("Error while updating docker files: %s", err)
		}
	}

	return nil
}

func generateGitHubConfig(repo Repository, targetDir string) error {
	target := filepath.Join(targetDir, gitHubDir)
	log.Printf("Generate github manifests in %s\n", target)
	if err := os.MkdirAll(filepath.Join(target, "workflows"), 0o755); err != nil {
		return err
	}

	autoMergeTemplateFile := "auto-merge-upstream.yaml"
	updateSourcesTemplateFile := "update-sources.yaml"

	autoMergeWorkflowFile := autoMergeTemplateFile
	updateSourcesWorkflowFile := updateSourcesTemplateFile
	if repo.Branch.Name == "main" {
		_, err := run(context.Background(), ".github", "cp", "renovate.json", target)
		if err != nil {
			return err
		}
		updateSourcesTemplateFile = "update-sources-all.yaml"
		autoMergeTemplateFile = "auto-merge-upstream-all.yaml"

		if len(repo.Owners) > 0 {
			if err := generateFileFromTemplate("slack-notify-on-failure.yaml", repo, filepath.Join(target, "workflows", "slack-notify-on-failure.yaml"), repo.Application); err != nil {
				return err
			}
		}
	}

	if repo.Upstream != "" {
		if err := generateFileFromTemplate(autoMergeTemplateFile, repo, filepath.Join(target, "workflows", autoMergeWorkflowFile), repo.Application); err != nil {
			return err
		}
		if err := generateFileFromTemplate(updateSourcesTemplateFile, repo, filepath.Join(target, "workflows", updateSourcesWorkflowFile), repo.Application); err != nil {
			return err
		}
	}

	return nil
}

func generateKonfluxConfig(application Application) error {
	if application.Release.Version == "main" {
		return nil
	}
	targetDir := filepath.Join(konfluxDir, application.Config.Product, hyphenize(application.Release.Version), application.Name)
	err := cleanupAutogenerated(context.Background(), application, targetDir)
	if err != nil {
		return err
	}

	log.Printf("Delete Konflux dir in %s\n", targetDir)
	if err := os.RemoveAll(targetDir); err != nil {
		return err
	}

	if err := generateKonfluxApplication(application, targetDir); err != nil {
		return err
	}

	pyxisDir := getPyxisDir(application)
	if pyxisDir != "" {
		err := cleanupAutogenerated(context.Background(), application, pyxisDir)
		if err != nil {
			return err
		}
	}

	if err := generateKonfluxComponents(application, targetDir); err != nil {
		return err
	}

	return nil
}

func generateKonfluxApplication(application Application, targetDir string) error {
	if err := generateFileFromTemplate("application.yaml", application, filepath.Join(targetDir, "application.yaml"), application); err != nil {
		return err
	}
	if err := generateFileFromTemplate("tests.yaml", application, filepath.Join(targetDir, "tests.yaml"), application); err != nil {
		return err
	}
	log.Printf("Create Release Tests in %s\n", targetDir)
	if strings.Contains(application.Name, "index") {
		for arch, instanceType := range instanceTypes {
			application.InstanceType = instanceType
			application.InstanceArch = arch
			if err := generateFileFromTemplate("release-tests.yaml", application, filepath.Join(targetDir, arch+"-release-tests.yaml"), application); err != nil {
				return err
			}
		}

	}
	if err := generateFileFromTemplate("release-plan.yaml", application, filepath.Join(targetDir, "release-plan.yaml"), application); err != nil {
		return err
	}
	_, err := strconv.ParseFloat(application.Release.Version, 64)
	if err == nil {
		rpaTargetDir := filepath.Join(konfluxDir, application.Config.RPADir)
		cdnProductDir := filepath.Join(konfluxDir, application.Config.CdnProductDir)
		var templateFile string
		if application.ShortName == "fbc" {
			templateFile = "release-plan-admission-fbc.yaml"
		} else {
			templateFile = "release-plan-admission.yaml"
		}

		if application.ShortName == "core" {
			if err := generateFileFromTemplate("product-cdn.yaml", application, filepath.Join(cdnProductDir, fmt.Sprintf("%s.yaml", strings.TrimPrefix(application.Release.FullVersion(), "v"))), application); err != nil {
				return err
			}
		}
		for env, _ := range releaseEnvironments {
			rpaFile := fmt.Sprintf("%s-%s-%s-%s.yaml", application.Config.Product, hyphenize(application.Release.Version), application.ShortName, env)
			rpaCdnFile := fmt.Sprintf("%s-%s-%s-%s-%s.yaml", application.Config.Product, hyphenize(application.Release.Version), application.ShortName, "cdn", env)
			templateData := struct {
				Application // Embedded (no field name)
				Env         string
			}{
				Application: application,
				Env:         env,
			}
			if err := generateFileFromTemplate(templateFile, templateData, filepath.Join(rpaTargetDir, rpaFile), application); err != nil {
				return err
			}
			releasePlanFile := fmt.Sprintf("%s-%s-%s-%s-rp.yaml", application.Config.Product, hyphenize(application.Release.Version), application.ShortName, env)
			if err := generateFileFromTemplate("release-plan-managed.yaml", templateData, filepath.Join(targetDir, releasePlanFile), application); err != nil {
				return err
			}
			if application.ShortName == "core" {
				cdnReleasePlanFile := fmt.Sprintf("%s-%s-%s-%s-%s-rp.yaml", application.Config.Product, hyphenize(application.Release.Version), application.ShortName, "cdn", env)
				if err := generateFileFromTemplate("release-plan-admission-cdn.yaml", templateData, filepath.Join(rpaTargetDir, rpaCdnFile), application); err != nil {
					return err
				}
				if err := generateFileFromTemplate("release-plan-cdn.yaml", templateData, filepath.Join(targetDir, cdnReleasePlanFile), application); err != nil {
					return err
				}
			}
		}

	}
	if err := generateFileFromTemplate("service-account.yaml", application, filepath.Join(targetDir, "service-account.yaml"), application); err != nil {
		return err
	}
	if err := generateFileFromTemplate("role.yaml", application, filepath.Join(targetDir, "role.yaml"), application); err != nil {
		return err
	}

	return nil
}

func generateKonfluxComponents(application Application, targetDir string) error {
	log.Printf("Generate %s konflux configuration in %s\n", application.Name, targetDir)
	for _, c := range application.Components {
		componentDir := filepath.Join(targetDir, c.Repository.Name)
		if err := generateFileFromTemplate("component.yaml", c, filepath.Join(componentDir, fmt.Sprintf("component-%s-%s.yaml", c.Name, application.Release.Version)), application); err != nil {
			return err
		}
		if err := generateFileFromTemplate("image.yaml", c, filepath.Join(componentDir, fmt.Sprintf("image-%s-%s.yaml", c.Name, application.Release.Version)), application); err != nil {
			return err
		}
		pyxisDir := getPyxisDir(application)
		if pyxisDir != "" {
			log.Printf("Generating Pyxis Config for %s\n", application.Name)

			if err := generateFileFromTemplate("pyxis-repo-config.yaml", c, filepath.Join(pyxisDir, fmt.Sprintf("image-%s.yaml", c.Image)), application); err != nil {
				return err
			}
		}

	}

	return nil
}

func getPyxisDir(application Application) string {
	if application.Release.Version == "nightly" && application.ShortName == "core" {
		return filepath.Join(konfluxDir, application.Config.PyxisConfigDir, strings.TrimPrefix(application.Release.ImageSuffix, "-"))
	} else {
		return ""
	}
}

// cleanupAutogenerated removes any files in the given directory's given subdirs which are marked as autogenerated to the given Konflux application
func cleanupAutogenerated(ctx context.Context, application Application, dir string, subdirs ...string) error {
	cleanupHeader := "# Generated for Konflux Application {{.Name}}"
	log.Printf("Cleanup Konflux configuration in %s\n", dir)
	if len(subdirs) == 0 {
		subdirs = append(subdirs, ".")
	}
	for _, subdir := range subdirs {
		log.Printf("Cleaning up %s\n", subdir)
		autoGeneratedHeader, _ := Eval(cleanupHeader, application)
		if out, err := run(ctx, dir, "grep", "-rl", autoGeneratedHeader, subdir); err != nil {
			log.Printf("Couldn't grep for autogenerated content, Error: %v,  Output: %s", err, out)
		} else {
			for _, f := range strings.Split(string(out), "\n") {
				if f == "" {
					continue
				}
				if err := os.Remove(filepath.Join(dir, f)); err != nil {
					return fmt.Errorf("couldn't remove autogenerated file %s: %w", f, err)
				}
			}
		}
	}

	return nil
}
