package konflux

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

const baseBranchPrefix = "hack/"

func cloneAndCheckout(ctx context.Context, repo Repository, targetDir string) (string, error) {
	branch := repo.Branch.Name
	branchPrefix := baseBranchPrefix + repo.Application.Name + "/"
	dir := filepath.Join(targetDir, repo.Application.Release.Version, repo.Name)
	exists, err := exists(filepath.Join(dir, ".git"))

	if err != nil {
		return dir, err
	}
	if exists {
		// Repository exists, fetch the latest changes
		if out, err := run(ctx, dir, "git", "fetch", "--all"); err != nil {
			return dir, fmt.Errorf("failed to fetch repository: %s, %s", err, out)
		}
	} else {
		// Repository does not exist, clone the repository
		if err := os.MkdirAll(dir, 0755); err != nil {
			return "", err
		}
		if out, err := run(ctx, dir, "git", "clone", repo.Url, "."); err != nil {
			return dir, fmt.Errorf("failed to clone repository: %s, %s", err, out)
		}
	}

	if out, err := run(ctx, dir, "git", "reset", "--hard", "HEAD", "--"); err != nil {
		return dir, fmt.Errorf("failed to reset %s branch: %s, %s", branch, err, out)
	}
	out, err := run(ctx, dir, "git", "ls-remote", "--heads", "origin", branch)
	if err != nil {
		return dir, fmt.Errorf("failed to reset %s branch: %s, %s", branch, err, out)
	}
	if len(out) == 0 {
		prevBranch, err := previousReleaseBranch(ctx, dir, branch)
		if err != nil {
			return dir, fmt.Errorf("failed to find previous release branch for %s: %s", branch, err)
		}
		if out, err := run(ctx, dir, "git", "switch", "-C", branch, "origin/"+prevBranch); err != nil {
			return dir, fmt.Errorf("failed to checkout branch for PR: %s, %s", err, out)
		}
		if out, err := run(ctx, dir, "git", "push", "-u", "origin", branch); err != nil {
			return dir, fmt.Errorf("failed to create branch for PR: %s, %s", err, out)
		}
	}
	if out, err := run(ctx, dir, "git", "checkout", "origin/"+branch, "-B", branch); err != nil {
		return dir, fmt.Errorf("failed to checkout %s branch: %s, %s", branch, err, out)
	}
	if out, err := run(ctx, dir, "git", "checkout", "-B", branchPrefix+branch); err != nil {
		return dir, fmt.Errorf("failed to checkout branch for PR: %s, %s", err, out)
	}
	return dir, nil
}

var releaseVersionRe = regexp.MustCompile(`^release-v(\d+)\.(\d+)\.x$`)

// previousReleaseBranch finds the highest release-vX.Y.x branch in the remote
// that is strictly older than targetBranch. Fails if the target is not a
// versioned release branch or no older branch exists.
func previousReleaseBranch(ctx context.Context, dir, targetBranch string) (string, error) {
	m := releaseVersionRe.FindStringSubmatch(targetBranch)
	if m == nil {
		return "", fmt.Errorf("branch %q is not a versioned release branch (expected release-vX.Y.x)", targetBranch)
	}
	targetMajor, _ := strconv.Atoi(m[1])
	targetMinor, _ := strconv.Atoi(m[2])

	out, err := run(ctx, dir, "git", "ls-remote", "--heads", "origin", "release-v*.x")
	if err != nil {
		return "", fmt.Errorf("failed to list remote release branches: %s", err)
	}

	type version struct {
		major, minor int
		name         string
	}
	var candidates []version
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		parts := strings.SplitN(line, "\t", 2)
		if len(parts) != 2 {
			continue
		}
		name := strings.TrimPrefix(parts[1], "refs/heads/")
		sm := releaseVersionRe.FindStringSubmatch(name)
		if sm == nil {
			continue
		}
		maj, _ := strconv.Atoi(sm[1])
		min, _ := strconv.Atoi(sm[2])
		if maj < targetMajor || (maj == targetMajor && min < targetMinor) {
			candidates = append(candidates, version{maj, min, name})
		}
	}
	if len(candidates) == 0 {
		return "", fmt.Errorf("no previous release branch found for %s", targetBranch)
	}
	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].major != candidates[j].major {
			return candidates[i].major > candidates[j].major
		}
		return candidates[i].minor > candidates[j].minor
	})
	return candidates[0].name, nil
}

// metadataTrailer generates and returns a string of metadata about the github workflow running the command
func metadataTrailer() string {
	message := ""

	if workflow := os.Getenv("GITHUB_WORKFLOW"); workflow != "" {
		message += fmt.Sprintf("\nGenerated by workflow [%s](%s/%s/actions/runs/%s)",
			workflow,
			os.Getenv("GITHUB_SERVER_URL"),
			os.Getenv("GITHUB_REPOSITORY"),
			os.Getenv("GITHUB_RUN_ID"),
		)
	}

	actor := os.Getenv("GITHUB_TRIGGERING_ACTOR")
	if os.Getenv("GITHUB_EVENT_NAME") == "schedule" {
		actor = "schedule"
	}

	if actor != "" {
		message += fmt.Sprintf("\nTriggered by %s", actor)
	}

	if message != "" {
		return "\n" + message
	}

	return ""
}

func commitAndPullRequest(ctx context.Context, repo Repository, dir string) error {
	branchPrefix := baseBranchPrefix + repo.Application.Name + "/"
	base := repo.Branch.Name
	head := branchPrefix + base

	if out, err := run(ctx, dir, "git", "status", "--porcelain"); err != nil {
		return fmt.Errorf("failed to check git status: %s, %s", err, out)
	} else if string(out) == "" {
		log.Printf("[%s] No changes, skipping commit and PR", dir)
		return nil
	}
	if out, err := run(ctx, dir, "bash", "-c", "git config user.name openshift-pipelines-bot; git config user.email pipelines-extcomm@redhat.com"); err != nil {
		return fmt.Errorf("failed to set some git configurations: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "add", "."); err != nil {
		return fmt.Errorf("failed to add: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "commit", "-m", fmt.Sprintf("[bot:%s] update konflux configuration%s", base, metadataTrailer())); err != nil {
		return fmt.Errorf("failed to commit: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "push", "-f", "origin", head); err != nil {
		return fmt.Errorf("failed to push: %s, %s", err, out)
	}

	cmd := fmt.Sprintf("gh pr list --base %s --head %s --json number --jq '.[0].number'", base, head)
	out, err := run(ctx, dir, "bash", "-c", cmd)

	if err != nil {
		return fmt.Errorf("failed to check if a pr exists: %s, %s", err, out)
	}
	prNumber := strings.TrimSpace(string(out))
	if prNumber == "" {
		log.Printf("No PR found for %s, Creating ", head)
		if out, err := run(ctx, dir, "gh", "pr", "create",
			"--base", base,
			"--head", head,
			"--label=hack", "--label=automated",
			"--title", fmt.Sprintf("[bot:%s] update konflux configuration", head),
			"--body", "This PR was automatically generated by the konflux command from openshift-pipelines/hack repository"+metadataTrailer()); err != nil {
			return fmt.Errorf("failed to create the pr: %s, %s", err, out)
		}
	} else {
		log.Printf("[%s] PR already exists", prNumber)
	}
	return nil
}

func exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	return false, err
}
