package main

import (
	"context"
	"errors"
	"fmt"
	k "github.com/openshift-pipelines/hack/internal/konflux"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const baseBranchPrefix = "actions/update/konflux-configuration-"

func cloneAndCheckout(ctx context.Context, repo, branch, dir string, config k.Config) error {
	branchPrefix := baseBranchPrefix + config.Name
	exists, err := exists(filepath.Join(dir, ".git"))

	if err != nil {
		return err
	}
	if exists {
		// Repository exists, fetch the latest changes
		if out, err := run(ctx, dir, "git", "fetch", "--all"); err != nil {
			return fmt.Errorf("failed to fetch repository: %s, %s", err, out)
		}
	} else {
		// Repository does not exist, clone the repository
		if out, err := run(ctx, dir, "git", "clone", repo, "."); err != nil {
			return fmt.Errorf("failed to clone repository: %s, %s", err, out)
		}
	}

	if out, err := run(ctx, dir, "git", "reset", "--hard", "HEAD", "--"); err != nil {
		return fmt.Errorf("failed to reset %s branch: %s, %s", branch, err, out)
	}
	out, err := run(ctx, dir, "git", "ls-remote", "--heads", "origin", branch)
	if err != nil {
		return fmt.Errorf("failed to reset %s branch: %s, %s", branch, err, out)
	}
	if len(out) == 0 {
		if _, err := run(ctx, dir, "git", "switch", "-C", branch, "origin/next"); err != nil {
			if out, err := run(ctx, dir, "git", "switch", "-C", branch, "origin/main"); err != nil {
				return fmt.Errorf("failed to checkout branch for PR: %s, %s", err, out)
			}
		}
		if out, err := run(ctx, dir, "git", "push", "-u", "origin", branch); err != nil {
			return fmt.Errorf("failed to create branch for PR: %s, %s", err, out)
		}
	}
	if out, err := run(ctx, dir, "git", "checkout", "origin/"+branch, "-B", branch); err != nil {
		return fmt.Errorf("failed to checkout %s branch: %s, %s", branch, err, out)
	}
	if out, err := run(ctx, dir, "git", "checkout", "-B", branchPrefix+branch); err != nil {
		return fmt.Errorf("failed to checkout branch for PR: %s, %s", err, out)
	}
	return nil
}

func commitAndPullRequest(ctx context.Context, dir, branch string, config k.Config) error {
	branchPrefix := baseBranchPrefix + config.Name

	if out, err := run(ctx, dir, "git", "status", "--porcelain"); err != nil {
		return fmt.Errorf("failed to check git status: %s, %s", err, out)
	} else if string(out) == "" {
		log.Printf("[%s] No changes, skipping commit and PR", dir)
		return nil
	}
	if out, err := run(ctx, dir, "bash", "-c", "git config user.name openshift-pipelines-bot; git config user.email pipelines-extcomm@redhat.com"); err != nil {
		return fmt.Errorf("failed to set some git configurations: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "add", "."); err != nil {
		return fmt.Errorf("failed to add: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "commit", "-m", fmt.Sprintf("[bot:%s] update konflux configuration", branch)); err != nil {
		return fmt.Errorf("failed to commit: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "git", "push", "-f", "origin", branchPrefix+branch); err != nil {
		return fmt.Errorf("failed to push: %s, %s", err, out)
	}
	if out, err := run(ctx, dir, "bash", "-c", "gh pr list --base "+branch+" --head "+branchPrefix+branch+" --json url --jq 'length'"); err != nil {
		return fmt.Errorf("failed to check if a pr exists: %s, %s", err, out)
	} else if strings.TrimSpace(string(out)) == "0" {
		if out, err := run(ctx, dir, "gh", "pr", "create",
			"--base", branch,
			"--head", branchPrefix+branch,
			"--label=hack", "--label=automated",
			"--title", fmt.Sprintf("[bot:%s:%s] update konflux configuration", config.Name, branch),
			"--body", "This PR was automatically generated by the konflux command from openshift-pipelines/hack repository"); err != nil {
			return fmt.Errorf("failed to create the pr: %s, %s", err, out)
		}
	}
	return nil
}

func exists(path string) (bool, error) {
	_, err := os.Stat(path)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, fs.ErrNotExist) {
		return false, nil
	}
	return false, err
}
