---
versionName: "{{ .Release.FullVersion | trimPrefix "v" }}"
ga: {{ hasSuffix .Release.FullVersion "0" }}
termsAndConditions: "Anonymous Download" # "Basic"
hidden: false
invisible: false
releaseDate: "2026-01-01"
