{{- $dot := .}}
{{- $policy := "registry-standard" -}}
{{- if eq .Config.Namespace "tekton-ecosystem-tenant" -}}
  {{- $policy = "registry-tekton-ecosystem" -}}
{{- end -}}
{{- $intention := "production"}}
{{- $serviceAccountName := "release-registry-prod" }}
{{- $registry := "registry.redhat.io/openshift-pipelines" -}}
{{- if ne .Env "prod" -}}
  {{- $policy = printf "%s-%s" $policy .Env -}}
  {{- $registry = "registry.stage.redhat.io/openshift-pipelines" -}}
  {{- $intention = "staging"}}
  {{- $serviceAccountName = "release-registry-staging"}}
{{- end -}}

---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleasePlanAdmission
metadata:
  labels:
    release.appstudio.openshift.io/block-releases: "false"
    pp.engineering.redhat.com/business-unit: application-developer
  name: {{.Config.Product}}-{{.Release.Version | hyphenize}}-{{.ShortName}}-{{.Env}}
  namespace: rhtap-releng-tenant
  annotations:
    rhel_target: {{.Application.Release.ImageSuffix | trimPrefix "-rh"}}
spec:
  applications:
    - {{.Name }}-{{.Release.Version | hyphenize}}
  origin: {{.Config.Namespace}}
  policy: {{$policy}}
  data:
    releaseNotes:
      product_id: [ 604 ]
      product_name: "Red Hat OpenShift Pipelines"
      product_version: "{{.Release.Version}}"
  {{- if .Components }}
    mapping:
      components:
  {{- range $component := .Components }}
        - name: {{basename .Repository.Name | hyphenize}}-{{hyphenize .Version.Version}}-{{hyphenize .Name}}
          repositories:
            - url: "{{printf "%s/%s" $registry .Image}}"
          pushSourceContainer: true
  {{- end }}
  {{- end }}
      defaults:
        tags:
          - "{{ "{{ git_sha }}" }}"
          - "{{ "{{ git_short_sha }}" }}"
          - "{{.Release.Version  }}{{ "-{{ timestamp }}" }}"
        pushSourceContainer: true
    intention: {{ $intention }}
    enforceContainerFirstSecurityLabels: true
  pipeline:
    serviceAccountName: {{$serviceAccountName}}
    timeouts:
      pipeline: "10h0m0s"
      tasks: 10h0m0s
    pipelineRef:
      resolver: git
      params:
        - name: url
          value: "https://github.com/konflux-ci/release-service-catalog.git"
        - name: revision
          value: production
        - name: pathInRepo
          value: "pipelines/managed/rh-advisories/rh-advisories.yaml"
