---
apiVersion: appstudio.redhat.com/v1beta2
kind: IntegrationTestScenario
metadata:
  name: {{hyphenize .Name}}-{{hyphenize .Release.Version}}-enterprise-contract
spec:
  application: {{hyphenize .Name}}-{{hyphenize .Release.Version}}
  contexts:
    - description: execute the integration test for a component
      name: component
  params:
    - name: POLICY_CONFIGURATION
      value: {{- if  not (contains "index" .Name ) }} tekton-ecosystem-tenant/tekton-ecosystem-tenant-containers {{- else}} tekton-ecosystem-tenant/tekton-ecosystem-tenant-indexes {{- end}}
    - name: TIMEOUT
      value: "15m0s"
    - name: SINGLE_COMPONENT
      value: "true"
  resolverRef:
    params:
      - name: url
        value: "https://github.com/konflux-ci/build-definitions"
      - name: revision
        value: main
      - name: pathInRepo
        value: pipelines/enterprise-contract.yaml
    resolver: git
