name: operator
components:
  - name: index-4.15
    dockerfile: .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: (".konflux/patches/***".pathChanged() || ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: main
    versions:
      - main
