name: operator
components:
  - name: index-4.13
    dockerfile: .konflux/olm-catalog/index/v4.13/Dockerfile.catalog
    nudges: [ "" ]
tekton:
  watched-sources: (".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: release-v1.16.x
    versions:
      - "1.16"
