name: operator
components:
  - name: index-4-18
    dockerfile: .konflux/olm-catalog/index/v4.18/Dockerfile.catalog
    image-prefix: operator-
    nudges: [ "" ]
  - name: index-4-17
    dockerfile: .konflux/olm-catalog/index/v4.17/Dockerfile.catalog
    image-prefix: operator-
    nudges: [ "" ]
  - name: index-4-16
    dockerfile: .konflux/olm-catalog/index/v4.16/Dockerfile.catalog
    image-prefix: operator-
    nudges: [ "" ]
  - name: index-4-15
    dockerfile: .konflux/olm-catalog/index/v4.15/Dockerfile.catalog
    image-prefix: operator-
    nudges: [ "" ]
tekton:
  watched-sources: (".konflux/patches/***".pathChanged() || ".konflux/olm-catalog/index/***".pathChanged())
branches:
  - name: next
    versions:
      - next
