name: operator
upstream: tektoncd/operator
components:
  - name: operator
  - name: webhook
  - name: proxy
  - name: bundle
    dockerfile: .konflux/olm-catalog/bundle/Dockerfile
    nudges:
      - operator-{{hyphenize .Version.Version}}-index-4-12
      - operator-{{hyphenize .Version.Version}}-index-4-13
      - operator-{{hyphenize .Version.Version}}-index-4-14
      - operator-{{hyphenize .Version.Version}}-index-4-15
      - operator-{{hyphenize .Version.Version}}-index-4-16
      - operator-{{hyphenize .Version.Version}}-index-4-17
      - operator-{{hyphenize .Version.Version}}-index-4-18
    tekton:
      watched-sources: (".konflux/patches/***".pathChanged() || ".konflux/olm-catalog/bundle/***".pathChanged())
patches: &patches
  - name: go1.23
    script: |
      rm ../.konflux/patches/0000-go1.23.patch || true

      # Change 'go 1.23.8' to 'go 1.23.6' in go.mod 
      sed -i 's|^go 1\.23\.8$|go 1.23.6|' go.mod

      # Change 'toolchain go1.24.x' to 'toolchain go1.23' in go.mod
      sed -i 's|^toolchain go1\.24\..*$|toolchain go1.23|' go.mod

      # Change 'go 1.23.8' to 'go 1.23.6' in vendor/modules.txt (within comments or specific lines)
      sed -i 's|go 1\.23\.8|go 1.23.6|g' vendor/modules.txt

      if [[ -z $(git status --porcelain --untracked-files=no) ]]; then
            echo "No change, exiting"
            exit 0
      else
        git diff > ../.konflux/patches/0000-go1.23.patch
      fi
      # clean after yourself >:D
      git checkout HEAD go.mod vendor/modules.txt
tekton:
  watched-sources: '"upstream/***".pathChanged() || ".konflux/patches/***".pathChanged() || ".konflux/rpms/***".pathChanged()'
github:
  update-sources: |
    - name: fetch-payload
      run: |
        pushd upstream
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        popd

        if [[ "$BRANCH_NAME" != "main" ]] && [[ -z $(git status --porcelain --untracked-files=no) ]]; then
          echo "No change, do nothing"
          # exit 0
        fi
        # Operator SDK
        export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.37.0/operator-sdk_linux_amd64
        curl -LO ${OPERATOR_SDK_DL_URL}
        chmod +x operator-sdk_linux_amd64 && sudo mv operator-sdk_linux_amd64 /usr/local/bin/operator-sdk

        operator-sdk version

        # Python with requirements (yaml here)
        # We could migrate to go...
        python3 -m venv sync-sources
        source sync-sources/bin/activate
        pip3 install -r requirements.txt

        # Update operator's payload and stuff
        make update-payload-and-reference
        pushd upstream
        rm -fR cmd/openshift/operator/kodata operatorhub
        git checkout HEAD .
        popd
branches:
  - name: next
    upstream: release-v0.76.x
    patches: *patches
    versions:
      - next
