apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-plan-role-1.17
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - snapshots
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-plan-rolebinding-1.17
subjects:
- kind: ServiceAccount
  name: release-registry-openshift-pipelines-1.17
  apiGroup: ""
roleRef:
  kind: Role
  name: release-plan-role-1.17
  apiGroup: rbac.authorization.k8s.io
