apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-index-1-22
  generateName: openshift-pipelines-index-1-22-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  gracePeriodDays: 10
  releasePlan: openshift-pipelines-1-22-fbc-stage-release-as-op
  snapshot: openshift-pipelines-index-1-22-20260416-022833-000-2v
