apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  labels:
    appstudio.openshift.io/application: openshift-pipelines-core-1-20
  generateName: openshift-pipelines-1-20-core-cdn-stage-release-
  namespace: tekton-ecosystem-tenant
spec:
  data:
  gracePeriodDays: 10
  releasePlan:  openshift-pipelines-core-1-20-cdn-stage-release-as-op
  snapshot: openshift-pipelines-core-1-20-20260520-063043-000-zh
