name: Global Org PR Merger
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day
  workflow_dispatch:      # Allows you to trigger it manually

jobs:
  bulk-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Process All Repos
        env:
          GH_TOKEN: ${{ secrets.ORG_ADMIN_TOKEN }}
          ORG_NAME: "openshift-pipelines"
          TARGET_LABEL: "hack"
        run: |
          echo "Get List of Repos "
          REPOS=$(yq -N e 'env(ORG_NAME)+"/"+.repo // .name' config/downstream/repos/*.yaml | sort -u)
          for REPO in $REPOS; do
            echo "Searching $REPO for PRs with label: $TARGET_LABEL"          
            PR_NUMS=$(gh pr list -R "$REPO" --label "$TARGET_LABEL" --json number --jq '.[].number')
            for PR in $PR_NUMS; do
              echo "Attempting to merge PR #$PR in $REPO..."
              # 3. Merge using 'auto' to respect branch protections
              gh pr merge "$PR" -R "$REPO" --rebase --auto 
            done
          done