name: Release Action - Finalize RC
run-name: Finalize RC for version ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          Downstream Release Version. Eg: "1.22", "1.23"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  finalize-rc:
    uses: ./.github/workflows/release-manager.yaml
    with:
      action: finalize-rc
      version: ${{ github.event.inputs.version }}
    secrets:
      OPENSHIFT_PIPELINES_ROBOT: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}
