name: Release Action - New Patch
run-name: New Patch for version ${{ github.event.inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          Downstream Release Version. Eg: "1.22", "1.23"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  new-patch:
    uses: ./.github/workflows/release-manager.yaml
    with:
      action: new-patch
      version: ${{ github.event.inputs.version }}
    secrets:
      OPENSHIFT_PIPELINES_ROBOT: ${{ secrets.OPENSHIFT_PIPELINES_ROBOT }}
